import numpy as np
import pandas as pd
df_maintr=pd.read_csv("css_main_training.csv",sep=';')

df_maintest=pd.read_csv("css_main_test.csv",sep=';')

df_merg=pd.concat([df_maintr,df_maintest],ignore_index=True)
df_merg
df_fuel=pd.read_csv("fuel_prices.csv",sep=";")
df_fuel["Start_date"]=df_fuel["date"]

df_merg["temperature"]=df_merg["temperature"].str.replace(r'[^-+0-9/]',"")

df_merg["temperature"]=df_merg["temperature"].replace(["+2"],"2")
df_merg["temperature"]=df_merg["temperature"].replace("+14","14")
df_merg["temperature"]=df_merg["temperature"].replace("+5","5")
df_merg["temperature"]=df_merg["temperature"].replace("+5+7","6")
df_merg["temperature"]=df_merg["temperature"].replace("+11/+12","11.5")
df_merg["temperature"]=df_merg["temperature"].replace("+12","12")
df_merg["temperature"]=df_merg["temperature"].replace("+2+15","8.5")
df_merg["temperature"]=df_merg["temperature"].replace("+15","15")
df_merg["temperature"]=df_merg["temperature"].replace("0/+5","2.5")
df_merg["temperature"]=df_merg["temperature"].replace("+12/+16","14")
df_merg["temperature"]=df_merg["temperature"].replace("+3","3")
df_merg["temperature"]=df_merg["temperature"].replace("+10","10")
df_merg["temperature"]=df_merg["temperature"].replace("+12/+14","13")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+6","4")
df_merg["temperature"]=df_merg["temperature"].replace("+0/+4","2")
df_merg["temperature"]=df_merg["temperature"].replace("-18-20","-19")
df_merg["temperature"]=df_merg["temperature"].replace("+15+25","20")
df_merg["temperature"]=df_merg["temperature"].replace("+8","8")
df_merg["temperature"]=df_merg["temperature"].replace("+2+3","2.5")
df_merg["temperature"]=df_merg["temperature"].replace("+1","1")
df_merg["temperature"]=df_merg["temperature"].replace("+15/+20","17.5")
df_merg["temperature"]=df_merg["temperature"].replace("+2+4","3")
df_merg["temperature"]=df_merg["temperature"].replace("+4/+6","5")
df_merg["temperature"]=df_merg["temperature"].replace("+8+10","9")
df_merg["temperature"]=df_merg["temperature"].replace("+2+20","11")
df_merg["temperature"]=df_merg["temperature"].replace("+5/+25","15")
df_merg["temperature"]=df_merg["temperature"].replace("+10+20","15")
df_merg["temperature"]=df_merg["temperature"].replace("+13","13")
df_merg["temperature"]=df_merg["temperature"].replace("+2+8","5")
df_merg["temperature"]=df_merg["temperature"].replace("0+4","2")
df_merg["temperature"]=df_merg["temperature"].replace("+5/+15","10")
df_merg["temperature"]=df_merg["temperature"].replace('-19/-21',"-20")
df_merg["temperature"]=df_merg["temperature"].replace('+12/+18',"15")
df_merg["temperature"]=df_merg["temperature"].replace('+14+18',"16")
df_merg["temperature"]=df_merg["temperature"].replace('+10/+15',"12.5")
df_merg["temperature"]=df_merg["temperature"].replace('+9',"9")
df_merg["temperature"]=df_merg["temperature"].replace('+6',"6")
df_merg["temperature"]=df_merg["temperature"].replace('-20-24',"-22")
df_merg["temperature"]=df_merg["temperature"].replace('+2+7',"4.5")
df_merg["temperature"]=df_merg["temperature"].replace('+16',"16")
df_merg["temperature"]=df_merg["temperature"].replace('+20',"20")
df_merg["temperature"]=df_merg["temperature"].replace('+18',"18")
df_merg["temperature"]=df_merg["temperature"].replace('-18/+5',"-6.5")
df_merg["temperature"]=df_merg["temperature"].replace('+21',"21")
df_merg["temperature"]=df_merg["temperature"].replace('0+2',"1")
df_merg["temperature"]=df_merg["temperature"].replace('+1/+2',"1.5")
df_merg["temperature"]=df_merg["temperature"].replace('+4',"4")
df_merg["temperature"]=df_merg["temperature"].replace("+10+25","17.5")
df_merg["temperature"]=df_merg["temperature"].replace("-18/-21","-19.5")
df_merg["temperature"]=df_merg["temperature"].replace("+14+20","+17")
df_merg["temperature"]=df_merg["temperature"].replace("-18/-25","-21.5")
df_merg["temperature"]=df_merg["temperature"].replace("+5+20","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+3/+4","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+3/+5","4")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+4","3")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+8","4")
df_merg["temperature"]=df_merg["temperature"].replace("+16+18","17")
df_merg["temperature"]=df_merg["temperature"].replace("2+6","4")
df_merg["temperature"]=df_merg["temperature"].replace("+7","7")
df_merg["temperature"]=df_merg["temperature"].replace("+12+25","18.5")
df_merg["temperature"]=df_merg["temperature"].replace("0100","5")
df_merg["temperature"]=df_merg["temperature"].replace("8-10","4.5")
df_merg["temperature"]=df_merg["temperature"].replace("+10/+35","22.5")
df_merg["temperature"]=df_merg["temperature"].replace("+15+18","16.5")
df_merg["temperature"]=df_merg["temperature"].replace("-12/-18","-15")
df_merg["temperature"]=df_merg["temperature"].replace("+5+30","17.5")
df_merg["temperature"]=df_merg["temperature"].replace("-18-24","-21")
df_merg["temperature"]=df_merg["temperature"].replace("+18/+22","20")
df_merg["temperature"]=df_merg["temperature"].replace("+1/+5","3")
df_merg["temperature"]=df_merg["temperature"].replace("+1+2","1.5")

df_merg["temperature"]=df_merg["temperature"].replace("1525","20")
df_merg["temperature"]=df_merg["temperature"].replace("525","15")
df_merg["temperature"]=df_merg["temperature"].replace("+4+8","6")
df_merg["temperature"]=df_merg["temperature"].replace("-10/-18","-14")
df_merg["temperature"]=df_merg["temperature"].replace("-18/-12","-15")
df_merg["temperature"]=df_merg["temperature"].replace("+22+23","22.5")
df_merg["temperature"]=df_merg["temperature"].replace("7-10","8.5")
df_merg["temperature"]=df_merg["temperature"].replace("7-15","11")
df_merg["temperature"]=df_merg["temperature"].replace("+8+15","11.5")
df_merg["temperature"]=df_merg["temperature"].replace("0/+4","11.5")
df_merg["temperature"]=df_merg["temperature"].replace("+5+10","7.5")
df_merg["temperature"]=df_merg["temperature"].replace("+12/+16+0/+4","16")
df_merg["temperature"]=df_merg["temperature"].replace("-20-23","-21.5")
df_merg["temperature"]=df_merg["temperature"].replace("+2+5","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+8+19","13.5")
df_merg["temperature"]=df_merg["temperature"].replace("+0","0")
df_merg["temperature"]=df_merg["temperature"].replace("2/6","4")
df_merg["temperature"]=df_merg["temperature"].replace("+3+5","4")
df_merg["temperature"]=df_merg["temperature"].replace("-22/+4","-9")
df_merg["temperature"]=df_merg["temperature"].replace("+0+2","1")
df_merg["temperature"]=df_merg["temperature"].replace("+4/+24","14")
df_merg["temperature"]=df_merg["temperature"].replace("+12+15","13.5")
df_merg["temperature"]=df_merg["temperature"].replace("+1+3","2")
df_merg["temperature"]=df_merg["temperature"].replace("+4+24","14")
df_merg["temperature"]=df_merg["temperature"].replace("0/15","7.5")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+5","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+10","6")
df_merg["temperature"]=df_merg["temperature"].replace("+3/+7","5")
df_merg["temperature"]=df_merg["temperature"].replace("+1/+3","2")
df_merg["temperature"]=df_merg["temperature"].replace("+5+18","11.5")
df_merg["temperature"]=df_merg["temperature"].replace("+5/+9","7")
df_merg["temperature"]=df_merg["temperature"].replace("15-25","20")
df_merg["temperature"]=df_merg["temperature"].replace("-22/-25","20")
df_merg["temperature"]=df_merg["temperature"].replace("+7/+10","8.5")
df_merg["temperature"]=df_merg["temperature"].replace("3/4","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("-25/-25","-25")
df_merg["temperature"]=df_merg["temperature"].replace("-25-18","-21.5")
df_merg["temperature"]=df_merg["temperature"].replace("+4-+8","6")
df_merg["temperature"]=df_merg["temperature"].replace("+19","19")
df_merg["temperature"]=df_merg["temperature"].replace("+1015","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+4-+6","5")
df_merg["temperature"]=df_merg["temperature"].replace("+5/+10","7.5")
df_merg["temperature"]=df_merg["temperature"].replace("+28-+30","29")
df_merg["temperature"]=df_merg["temperature"].replace("+15/+25","7.5")
df_merg["temperature"]=df_merg["temperature"].replace("+28","28")
df_merg["temperature"]=df_merg["temperature"].replace("+5/+20","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+8/+10","9")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+7","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+12+18","15")
df_merg["temperature"]=df_merg["temperature"].replace("2/4","3")
df_merg["temperature"]=df_merg["temperature"].replace("+10+12","11")
df_merg["temperature"]=df_merg["temperature"].replace("-16/-20","-18")
df_merg["temperature"]=df_merg["temperature"].replace("+2-+5","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+4+25","14.5")
df_merg["temperature"]=df_merg["temperature"].replace("+13-+18","15.5")
df_merg["temperature"]=df_merg["temperature"].replace("+3+4","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+18-+20","19")
df_merg["temperature"]=df_merg["temperature"].replace("10-25","17.5")
df_merg["temperature"]=df_merg["temperature"].replace("10-15+","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+0-+4","17.5")
df_merg["temperature"]=df_merg["temperature"].replace("+12-+16","14")
df_merg["temperature"]=df_merg["temperature"].replace("+12-+14","13")
df_merg["temperature"]=df_merg["temperature"].replace("0-+2","1")
df_merg["temperature"]=df_merg["temperature"].replace("+23","23")
df_merg["temperature"]=df_merg["temperature"].replace("+2-6","4")
df_merg["temperature"]=df_merg["temperature"].replace("+13/+15","14")
df_merg["temperature"]=df_merg["temperature"].replace("+17/+20","18.5")
df_merg["temperature"]=df_merg["temperature"].replace("+15-+25","20")
df_merg["temperature"]=df_merg["temperature"].replace("+10+40","25")
df_merg["temperature"]=df_merg["temperature"].replace("+0/+2","1")
df_merg["temperature"]=df_merg["temperature"].replace("+3/+6","4.5")
df_merg["temperature"]=df_merg["temperature"].replace("+100+15","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("5-35","20")
df_merg["temperature"]=df_merg["temperature"].replace("+5+35","20")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+3","2.5")
df_merg["temperature"]=df_merg["temperature"].replace("+10-+15","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+10/+18","14")
df_merg["temperature"]=df_merg["temperature"].replace("+20+/-5","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("-2+2","0")
df_merg["temperature"]=df_merg["temperature"].replace("+13/+14","13.5")
df_merg["temperature"]=df_merg["temperature"].replace("+2//+5","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+25","25")
df_merg["temperature"]=df_merg["temperature"].replace("-24/-18","-21")
df_merg["temperature"]=df_merg["temperature"].replace("+17","17")
df_merg["temperature"]=df_merg["temperature"].replace("-2/+2","0")
df_merg["temperature"]=df_merg["temperature"].replace("+10/+20","15")
df_merg["temperature"]=df_merg["temperature"].replace("+14/+16","15")
df_merg["temperature"]=df_merg["temperature"].replace("+0+30","15")
df_merg["temperature"]=df_merg["temperature"].replace("+7+9","8")
df_merg["temperature"]=df_merg["temperature"].replace("+17+24","20.5")
df_merg["temperature"]=df_merg["temperature"].replace("02","1")
df_merg["temperature"]=df_merg["temperature"].replace("+3+25","14")
df_merg["temperature"]=df_merg["temperature"].replace("0-4","2")
df_merg["temperature"]=df_merg["temperature"].replace("-22-18","-20")
df_merg["temperature"]=df_merg["temperature"].replace("-3-4","-3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+10+30","20")
df_merg["temperature"]=df_merg["temperature"].replace("-24-18","-21")
df_merg["temperature"]=df_merg["temperature"].replace("+5/+30","17.5")
df_merg["temperature"]=df_merg["temperature"].replace("+3+7","5")
df_merg["temperature"]=df_merg["temperature"].replace("+18+20","19")
df_merg["temperature"]=df_merg["temperature"].replace("+16+20","18")
df_merg["temperature"]=df_merg["temperature"].replace("+10+15","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("2/5","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("+7+10","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+4/+7","5.5")
df_merg["temperature"]=df_merg["temperature"].replace("+2+10","6")
df_merg["temperature"]=df_merg["temperature"].replace("+1+20","10.5")
df_merg["temperature"]=df_merg["temperature"].replace("+10+18","14")
df_merg["temperature"]=df_merg["temperature"].replace("-10-14","-12")
df_merg["temperature"]=df_merg["temperature"].replace("+5/+6","5.5")
df_merg["temperature"]=df_merg["temperature"].replace("+6+15","10.5")
df_merg["temperature"]=df_merg["temperature"].replace("+6+12","9")
df_merg["temperature"]=df_merg["temperature"].replace("-20/","-20")
df_merg["temperature"]=df_merg["temperature"].replace("+13+15","14")
df_merg["temperature"]=df_merg["temperature"].replace("0+5","2.5")
df_merg["temperature"]=df_merg["temperature"].replace("+11","11")
df_merg["temperature"]=df_merg["temperature"].replace("+4+6+5","5")
df_merg["temperature"]=df_merg["temperature"].replace("+4+30","17")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+21/","11.5")
df_merg["temperature"]=df_merg["temperature"].replace("+185","11.5")
df_merg["temperature"]=df_merg["temperature"].replace("+17+23","20")
df_merg["temperature"]=df_merg["temperature"].replace("+12+14","13")
df_merg["temperature"]=df_merg["temperature"].replace("+6+8","7")
df_merg["temperature"]=df_merg["temperature"].replace("-18-23","-20.5")
df_merg["temperature"]=df_merg["temperature"].replace("-18-22","-20")
df_merg["temperature"]=df_merg["temperature"].replace("0/+15","7.5")
df_merg["temperature"]=df_merg["temperature"].replace("2/+15","8.5")
df_merg["temperature"]=df_merg["temperature"].replace("+5+6","5.5")
df_merg["temperature"]=df_merg["temperature"].replace("+13+16","14.5")
df_merg["temperature"]=df_merg["temperature"].replace("+4/+8","6")
df_merg["temperature"]=df_merg["temperature"].replace("+5-+20","12.5")
df_merg["temperature"]=df_merg["temperature"].replace("+14/+20","17.5")
df_merg["temperature"]=df_merg["temperature"].replace("+2/+24","13")
df_merg["temperature"]=df_merg["temperature"].replace("5-7","6")
df_merg["temperature"]=df_merg["temperature"].replace("0/5","2.5")
df_merg["temperature"]=df_merg["temperature"].replace("+5+22","13.5")
df_merg["temperature"]=df_merg["temperature"].replace("0/-1","0.5")
df_merg["temperature"]=df_merg["temperature"].replace("+4+14","9")
df_merg["temperature"]=df_merg["temperature"].replace("+7/+15","11")
df_merg["temperature"]=df_merg["temperature"].replace("5-12","8.5")
df_merg["temperature"]=df_merg["temperature"].replace("/-18","-18")
df_merg["temperature"]=df_merg["temperature"].replace("-20-22","-21")
df_merg["temperature"]=df_merg["temperature"].replace("+3/4","3.5")
df_merg["temperature"]=df_merg["temperature"].replace("-19-25","22")
df_merg["temperature"]=df_merg["temperature"].replace("+6/+15","10.5")
df_merg["temperature"]=df_merg["temperature"].replace("+4+7","5.5")
df_merg["temperature"]=df_merg["temperature"].replace("+10-","10")
df_merg["temperature"]=df_merg["temperature"].replace("/","")
df_merg["temperature"]=df_merg["temperature"].replace("+5/7","6")
df_merg["temperature"]=df_merg["temperature"].replace("+12+16+14","14")
df_merg["temperature"]=df_merg["temperature"].replace("5-10+","7.5")
df_merg["temperature"]=df_merg["temperature"].replace("2+","2")
df_merg["temperature"]=df_merg["temperature"].replace("+10+20+15","15")
df_merg["temperature"]=df_merg["temperature"].replace("4/7","5.5")
df_merg["temperature"]=df_merg["temperature"].replace("05+","2.5")
df_merg["temperature"]=df_merg["temperature"].replace("2+4","3")
df_merg["temperature"]=df_merg["temperature"].replace("+12+10+14","12")
df_merg["temperature"]=df_merg["temperature"].replace("0+424+","2")
df_merg["temperature"]=df_merg["temperature"].replace("+2+/-2","0")
df_merg["temperature"]=df_merg["temperature"].replace("+28+","28")
df_merg["temperature"]=df_merg["temperature"].replace("0+4+2","2")
df_merg["temperature"]=df_merg["temperature"].replace("+814","11")
df_merg["temperature"]=df_merg["temperature"].replace("00+5","2.5")
df_merg["temperature"]=df_merg["temperature"].replace("+8+12","10")
df_merg["temperature"]=df_merg["temperature"].replace("+2+","2")
df_merg["temperature"]=df_merg["temperature"].replace("10-18+","9")
df_merg["temperature"]=df_merg["temperature"].replace("-25/","-25")
df_merg["temperature"]=df_merg["temperature"].replace("12+16+14","14")
df_merg["temperature"]=df_merg["temperature"].replace("2+4+","3")
df_merg["temperature"]=df_merg["temperature"].replace("+20+20","20")
df_merg["temperature"]=df_merg["temperature"].replace("-20-20","-20")
df_merg["temperature"]=df_merg["temperature"].replace('+10+20',"15")
df_merg["temperature"]=df_merg["temperature"].replace('+14/+18',"16")
df_merg["temperature"]=df_merg["temperature"].replace('0+15',"7.5")
df_merg["temperature"]=df_merg["temperature"].replace("+12+16","14")
df_merg["temperature"]=df_merg["temperature"].replace("+2+6","4")
df_merg["temperature"]=df_merg["temperature"].replace('-18/-20',"-19")
df_merg["temperature"]=df_merg["temperature"].replace('0/+2',"1")
df_merg["temperature"]=df_merg["temperature"].replace('+5+15',"10")
df_merg["temperature"]=df_merg["temperature"].replace('+15+20',"17.5")
df_merg["temperature"]=df_merg["temperature"].replace('+5+25',"15")

df_merg["temperature"]=df_merg["temperature"].replace('-18-25',"-21.5")
df_merg["temperature"]=df_merg["temperature"].replace('+2/+21',"11.5")
df_merg["temperature"]=df_merg["temperature"].replace('+2/+15',"13.5")
df_merg["temperature"]=df_merg["temperature"].replace('-/18',"-18")
df_merg["temperature"]=df_merg["temperature"].str.replace("/","")

df_merg["Start_date"] = pd.to_datetime(df_merg["route_start_datetime"]).dt.date
df_merg["Start_time"] = pd.to_datetime(df_merg["route_start_datetime"]).dt.time

df_merg["Start_date"]=df_merg["Start_date"].astype("str")

df_merg[["Start_year","Start_month","Start_day"]]=df_merg["Start_date"].str.split("-",expand = True)
df_merg=df_merg.merge(df_fuel,how="left",on="Start_date")

b=df_merg[(df_merg["refrigerated"]==1)&(df_merg["ferry_duration"]!=0)&(df_merg["Start_month"]=="07")  & (df_merg["first_load_country"]=="NL")& (df_merg["temperature"]!="")]["temperature"].astype(float)
df_merg.loc[df_merg[(df_merg["refrigerated"]==1)&(df_merg["ferry_duration"]!=0)&(df_merg["Start_month"]=="07")  & (df_merg["first_load_country"]=="NL")& (df_merg["temperature"]=="")]

c=df_merg[(df_merg["refrigerated"]==1)&(df_merg["ferry_duration"]!=0)&(df_merg["Start_month"]=="08")  & (df_merg["first_load_country"]=="NL")& (df_merg["temperature"]!="")]["temperature"].astype(float)
df_merg.loc[df_merg[(df_merg["refrigerated"]==1)&(df_merg["ferry_duration"]!=0)&(df_merg["Start_month"]=="08")  & (df_merg["first_load_country"]=="NL")& (df_merg["temperature"]=="")]

a=df_merg[(df_merg["temperature"]!="+") & (df_merg["temperature"]!="") & (df_merg["Start_month"]=="06") &(df_merg["Start_year"]=="2020")&(df_merg["refrigerated"]==1)]["temperature"].astype(float).mean()

df_merg.loc[df_merg[(df_merg["Start_month"]=="06") &(df_merg["Start_year"]=="2020")&(df_merg["refrigerated"]==1)&(df_merg["temperature"]=="+")].index[0],"temperature"]=round(a,1)

a=df_merg[(df_merg["temperature"]!="+") & (df_merg["temperature"]!="") & (df_merg["Start_month"]=="10") &(df_merg["Start_year"]=="2020")&(df_merg["refrigerated"]==1)]["temperature"].astype(float).mean()
df_merg.loc[df_merg[(df_merg["Start_month"]=="10") &(df_merg["Start_year"]=="2020")&(df_merg["refrigerated"]==1)&(df_merg["temperature"]=="+")].index[0],"temperature"]=round(a,1)

a=df_merg[(df_merg["temperature"]!="+") & (df_merg["temperature"]!="") & (df_merg["Start_month"]=="11") &(df_merg["Start_year"]=="2018")&(df_merg["refrigerated"]==1)]["temperature"].astype(float).mean()
df_merg.loc[df_merg[(df_merg["Start_month"]=="11") &(df_merg["Start_year"]=="2018")&(df_merg["refrigerated"]==1)&(df_merg["temperature"]=="+")].index[0],"temperature"]=round(a,1)
a=df_merg[(df_merg["temperature"]!="+") & (df_merg["temperature"]!="") & (df_merg["Start_month"]=="12") &(df_merg["Start_year"]=="2018")&(df_merg["refrigerated"]==1)]["temperature"].astype(float).mean()
df_merg.loc[df_merg[(df_merg["Start_month"]=="12") &(df_merg["Start_year"]=="2018")&(df_merg["refrigerated"]==1)&(df_merg["temperature"]=="+")].index[0],"temperature"]=round(a,1)
a=df_merg[(df_merg["temperature"]!="+") & (df_merg["temperature"]!="") & (df_merg["Start_month"]=="01") &(df_merg["Start_year"]=="2019")&(df_merg["refrigerated"]==1)]["temperature"].astype(float).mean()
df_merg.loc[df_merg[(df_merg["Start_month"]=="01") &(df_merg["Start_year"]=="2019")&(df_merg["refrigerated"]==1)&(df_merg["temperature"]=="+")].index[0],"temperature"]=round(a,1)
a=df_merg[(df_merg["temperature"]!="+") & (df_merg["temperature"]!="") & (df_merg["Start_month"]=="01") &(df_merg["Start_year"]=="2019")&(df_merg["refrigerated"]==1)]["temperature"].astype(float).mean()
df_merg.loc[df_merg[(df_merg["Start_month"]=="01") &(df_merg["Start_year"]=="2019")&(df_merg["refrigerated"]==1)&(df_merg["temperature"]=="+")].index[0],"temperature"]=round(a,1)
a=df_merg[(df_merg["temperature"]!="+") & (df_merg["temperature"]!="") & (df_merg["Start_month"]=="07") &(df_merg["Start_year"]=="2021")&(df_merg["refrigerated"]==1)]["temperature"].astype(float).mean()
df_merg.loc[df_merg[(df_merg["Start_month"]=="07") &(df_merg["Start_year"]=="2021")&(df_merg["refrigerated"]==1)&(df_merg["temperature"]=="+")].index[0],"temperature"]=round(a,1)

df_unclear=df_merg[(df_merg["temperature"]=='039862016') | (df_merg["temperature"]=="041782015") | (df_merg["temperature"]=='040912016') | (df_merg["temperature"]=="000642016") | (df_merg["temperature"]=="029012016") | (df_merg["temperature"]=="041152016") | (df_merg["temperature"]=="047382016") | (df_merg["temperature"]=="") |  (df_merg["temperature"]=="048532016") | (df_merg["temperature"]=="049382016") | (df_merg["temperature"]=="220544") | (df_merg["temperature"]=="929775") | (df_merg["temperature"]=="515866")]


for i in df_unclear[df_unclear["refrigerated"]==1].Start_year.unique():
    for j in df_unclear[df_unclear["refrigerated"]==1].Start_month.unique():
        a=df_merg[(df_merg["temperature"]!='039862016') & (df_merg["temperature"]!="041782015") & (df_merg["temperature"]!='040912016') & (df_merg["temperature"]!="000642016")& (df_merg["temperature"]!="029012016") & (df_merg["temperature"]!="041152016") & (df_merg["temperature"]!="047382016") & (df_merg["temperature"]!='') & (df_merg["refrigerated"]==1)  & (df_merg["temperature"]!="048532016") & (df_merg["temperature"]!="049382016") & (df_merg["temperature"]!="220544") & (df_merg["temperature"]!="929775") & (df_merg["temperature"]!="515866")]        
        b=a[(a["Start_year"]==str(i))& (a["Start_month"]==str(j))]["temperature"].astype(float).mean() 
        df_merg.loc[df_unclear[(df_unclear["Start_year"]==str(i)) & (df_unclear["Start_month"]==str(j))].index,"temperature"]=round(b,1)


df_merg["temperature"]=df_merg["temperature"].astype(float)

a=df_merg[(df_merg["temperature"]<=15)]["temperature"].mean()
b=df_merg[df_merg["temperature"].isnull()][df_merg["ferry_duration"]==0]["temperature"].index
df_merg.loc[b,"temperature"]=a

a=df_merg[(df_merg["temperature"]>=20)]["temperature"].mean()
b=df_merg[df_merg["temperature"].isnull()][df_merg["ferry_duration"]!=0]["temperature"].index
df_merg.loc[b,"temperature"]=a

df_merg[["BYR","CHF","CZK","DKK","EEK","EGP","EUR","GBP","HUF","LTL","NOK","PLN","RON","SEK","USD"]]=pd.get_dummies(df_merg["id_currency"])

df_final=df_merg[["expenses","refrigerated","temperature","euro_exchange_rate","BYR","CHF","CZK","DKK","EEK","EGP","EUR","GBP","HUF","LTL","NOK","PLN","RON","SEK","USD","km_empty","km_nonempty","train_km","ferry_duration","km_total","disel_type1_price","disel_type2_price","disel_type3_price"]]
df_final=df_final.astype(float)

df_final_train=df_final.iloc[:330055]
df_final_test=df_final.iloc[330055:]

X=df_final_train[["refrigerated","temperature","euro_exchange_rate","BYR","CHF","CZK","DKK","EEK","EGP","EUR","GBP","HUF","LTL","NOK","PLN","RON","SEK","USD","km_empty","km_nonempty","train_km","ferry_duration","km_total","disel_type1_price","disel_type2_price","disel_type3_price"]]
y=df_final_train["expenses"]

df_final_test=df_final_test[["refrigerated","temperature","euro_exchange_rate","BYR","CHF","CZK","DKK","EEK","EGP","EUR","GBP","HUF","LTL","NOK","PLN","RON","SEK","USD","km_empty","km_nonempty","train_km","ferry_duration","km_total","disel_type1_price","disel_type2_price","disel_type3_price"]]

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import SGDRegressor

lin_reg = LinearRegression()
lin_reg.fit(X, y)
y_pred = lin_reg.predict(df_final_test)

df_answer=pd.DataFrame(y_pred)
df_answer






